// Vectorizes the client's logo (../logo.JPG, gold on black) into flat SVG paths so it can be
// recolored with the site palette. Splits it into parts: rings, building mark and three text lines.
// Usage: node scripts/trace-logo.mjs   → writes src/data/logo.ts
import sharp from 'sharp';
import potrace from 'potrace';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const root = new URL('../', import.meta.url);
const source = fileURLToPath(new URL('../logo.JPG', root));

// Gold pixels → black shapes on white, which is what potrace traces.
const { data: mask, info } = await sharp(source).greyscale().threshold(70).negate().raw().toBuffer({ resolveWithObject: true });
const W = info.width, H = info.height;
const png = await sharp(mask, { raw: { width: W, height: H, channels: 1 } }).png().toBuffer();

const svg = await new Promise((resolve, reject) =>
  potrace.trace(png, { turdSize: 8, optTolerance: 0.25, alphaMax: 1, threshold: 128 }, (err, out) => (err ? reject(err) : resolve(out))),
);
const d = svg.match(/ d="([^"]+)"/)[1];

// The two rings sit far from the centre; the building and the lettering sit inside radius RING_R.
const CX = W / 2, CY = H / 2, RING_R = 515;
const inside = (x, y) => Math.hypot(x - CX, y - CY) < RING_R;
const ranges = { mark: [120, 790], line1: [790, 905], line2: [905, 990], line3: [990, 1100] };

// Bounding box of ink inside a horizontal band, ignoring the rings.
function bbox([y0, y1]) {
  let minX = W, maxX = 0, minY = H, maxY = 0;
  for (let y = y0; y < y1; y++) for (let x = 0; x < W; x++) {
    if (mask[y * W + x] < 128 && inside(x, y)) { if (x < minX) minX = x; if (x > maxX) maxX = x; if (y < minY) minY = y; if (y > maxY) maxY = y; }
  }
  return [minX, minY, maxX - minX + 1, maxY - minY + 1];
}
const bands = Object.fromEntries(Object.entries(ranges).map(([k, r]) => [k, bbox(r)]));

// Split the traced path into sub-paths and group them by where they start.
const subs = d.split(/(?=M)/).map(s => s.trim()).filter(Boolean);
const start = s => s.match(/^M\s*([-\d.]+)[ ,]+([-\d.]+)/).slice(1).map(Number);
const parts = { rings: [], mark: [], line1: [], line2: [], line3: [] };
for (const s of subs) {
  const [x, y] = start(s);
  const key = inside(x, y) ? Object.keys(ranges).find(k => y >= ranges[k][0] && y < ranges[k][1]) : undefined;
  parts[key ?? 'rings'].push(s);
}

const pad = ([x, y, w, h], m) => [x - m, y - m, w + 2 * m, h + 2 * m];
const out = {
  size: W,
  box: { badge: [36, 36, W - 72, H - 72], mark: pad(bands.mark, 4), line1: pad(bands.line1, 2), line2: pad(bands.line2, 2), line3: pad(bands.line3, 2) },
  paths: Object.fromEntries(Object.entries(parts).map(([k, v]) => [k, v.join(' ')])),
};

await writeFile(new URL('src/data/logo.ts', root), `// Generated by scripts/trace-logo.mjs from logo.JPG. Do not edit by hand.
// Coordinates are in the ${W}×${H} space of the original logo; boxes are [x, y, width, height].
export const LOGO = ${JSON.stringify(out)} as const;
`);
console.log('boxes', out.box);
console.log('sub-paths', Object.fromEntries(Object.entries(parts).map(([k, v]) => [k, v.length])));
console.log('path KB', Object.fromEntries(Object.entries(out.paths).map(([k, v]) => [k, Math.round(v.length / 1024)])));
